from sudoku import app
from .sudoku import Sudoku
from flask import render_template, request, url_for

NUM_OF_CELLS = 81

@app.route('/')
def home_page():
    return render_template('index.html')


@app.route('/solution', methods=['POST'])
def solution_page():
    data = request.form
    cleaned_data = clean_data(data)
    Su = Sudoku(cleaned_data)
    return cleaned_data


def clean_data(data):
    '''
    function to clean data generated by form into list of chars
    '''
    board = []

    i = 0
    while i < NUM_OF_CELLS:
        board_row = []
        for _ in range(9):
            key = f'cell-{i}'
            if(data[key]):
                board_row.append(data[key])
            else:
                board_row.append('.')

            i += 1
        board.append(board_row)

    return board